apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjcm5hZ3AuYXp1cmVjci5pbyI6IHt9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlZmF1bHQiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson



